app/models/post.py
from datetime import datetime
from app.extensions import db


class Post(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    teacher = db.Column(db.Integer, db.ForeignKey(
        'user.id', ondelete='CASCADE'))
    subject = db.Column(db.String(250))
    student = db.Column(db.Integer)
    date = db.Column(db.DateTime, default=datetime.utcnow)

app/models/user.py
from datetime import datetime
from app.extensions import db, login_manager
from flask_login import UserMixin

from app.models.post import Post


@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))


class User(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    posts = db.relationship(Post, backref='author')
    status = db.Column(db.String(50), default='user')
    name = db.Column(db.String(50))
    login = db.Column(db.String(50))
    password = db.Column(db.String(200))
    date = db.Column(db.DateTime, default=datetime.utcnow)
    avatar = db.Column(db.String(200))

app/forms.py
from flask_wtf import FlaskForm
from flask_wtf.file import FileAllowed

from wtforms import BooleanField, FileField, PasswordField, SelectField, StringField, SubmitField, ValidationError
from wtforms.validators import DataRequired, Length, EqualTo

from app.models.user import User


class RegistrationForm(FlaskForm):
    name = StringField('ФИО', validators=[
                       DataRequired(), Length(min=2, max=100)])
    login = StringField('Логин', validators=[
        DataRequired(), Length(min=2, max=20)], render_kw={
        'class': 'form-control',
        'placeholder': 'Логин'
    })
    password = PasswordField('Пароль', validators=[
        DataRequired()])
    confirm_password = PasswordField('Подтвердите пароль', validators=[
        DataRequired(), EqualTo('password')])
    avatar = FileField('Загрузите свое фото', validators=[
                       FileAllowed(['jpg', 'jpeg', 'png'])])
    submit = SubmitField('Зарегистрироваться')

    def validate_login(self, login):
        user = User.query.filter_by(login=login.data).first()
        if user:
            raise ValidationError(
                "Данное имя пользователя уже занято! Пожалуйста выберите другое имя пользователя.")
        
class LoginForm(FlaskForm):
    """Form to log in users"""
    login = StringField('Логин', validators=[DataRequired(), Length(min=2, max=20)])
    password = PasswordField('Пароль', validators=[DataRequired()])
    remember = BooleanField('Запомнить меня')
    submit = SubmitField('Войти')


class StudentForm(FlaskForm):
    student = SelectField('student', choices=[], render_kw={'class': 'form-control'})

app/__init__.py
from flask import Flask
from .extensions import db, migrate, login_manager
from .config import Config

from .routes.user import user
from .routes.post import post


def create_app(config_class=Config):
    app = Flask(__name__)
    app.config.from_object(config_class)

    app.register_blueprint(user)
    app.register_blueprint(post)

    db.init_app(app)
    migrate.init_app(app, db)
    login_manager.init_app(app)

    # LOGIN_MANAGER
    login_manager.login_view = 'user.login'
    login_manager.login_message = 'Вы не можете получить доступ к данной странице, для начала Авторизуйтесь!'
    login_manager.login_message_category = 'info'

    with app.app_context():
        db.create_all()

    return app

app/routes/post.py
from flask import Blueprint, render_template, request, redirect
from flask_login import current_user, login_required

from app.forms import StudentForm
from app.models.user import User
from ..models.post import Post
from ..extensions import db

post = Blueprint('post', __name__)


@post.route('/', methods=['POST', 'GET'])
def all():
    posts = Post.query.order_by(Post.date).all()
    return render_template('post/all.html', posts=posts)


@post.route('/post/create', methods=['POST', 'GET'])
@login_required
def create():
    form = StudentForm()
    form.student.choices = [
        student.name for student in User.query.filter_by(status='user')]
    if request.method == 'POST':
        subject = request.form.get('subject')
        student = request.form.get('student')

        student_id = User.query.filter_by(name=student).first().id

        post = Post(teacher=current_user.id, subject=subject, student=student_id)

        try:
            db.session.add(post)
            db.session.commit()
            return redirect('/')
        except Exception as e:
            print(str(e))

    else:
        return render_template('post/create.html', form=form)


@post.route('/post/<int:id>/update', methods=['POST', 'GET'])
@login_required
def update(id):
    post = Post.query.get(id)
    if request.method == 'POST':
        post.teacher = request.form.get('teacher')
        post.subject = request.form.get('subject')
        post.student = request.form.get('student')

        try:
            db.session.commit()
            return redirect('/')
        except Exception as e:
            print(str(e))
    else:
        return render_template('post/update.html', post=post)


@post.route('/post/<int:id>/delete', methods=['POST', 'GET'])
@login_required
def delete(id):
    post = Post.query.get(id)
    try:
        db.session.delete(post)
        db.session.commit()
        return redirect('/')
    except Exception as e:
        print(str(e))
        return str(e)

app/routes/user.py
from flask import Blueprint, render_template, redirect, flash, request, url_for
from flask_login import login_user, logout_user

from app.fucntions import save_picture
from app.models.user import User
from ..extensions import db, bcrypt
from ..forms import LoginForm, RegistrationForm

user = Blueprint('user', __name__)


@user.route('/user/register', methods=['POST', 'GET'])
def register():
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(
            form.password.data).decode('utf-8')
        avatar_filename = save_picture(form.avatar.data)
        user = User(name=form.name.data, login=form.login.data,
                    avatar=avatar_filename, password=hashed_password)
        try:
            db.session.add(user)
            db.session.commit()
            flash(f'Поздравляем, {
                  form.login.data}! Вы успешно зарегистрированы!', 'success')
            return redirect(url_for('user.login'))
        except Exception as e:
            print(str(e))
            flash(f'При регистрации произошла ошибка', 'danger')
    return render_template('user/register.html', form=form)


@user.route('/user/login', methods=['POST', 'GET'])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(login=form.login.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            next_page = request.args.get('next')
            flash(f'Поздравляем, {
                form.login.data}! Вы успешно авторизованы!', 'success')
            return redirect(next_page) if next_page else redirect(url_for('post.all'))
        else:
            flash(f'Ошибка входа. Пожалуйста проверьте логин и пароль!', 'danger')
    return render_template('user/login.html', form=form)


@user.route('/user/logout', methods=['POST', 'GET'])
def logout():
    logout_user()
    return redirect(url_for('post.all'))

app/templates/main/_flash.html
<!-- FLASH MESSAGES -->

{% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
        {% for category, message in messages %}
            <div class="alert alert-{{ category }}">
                {{ message }}
            </div>
        {% endfor %}
    {% endif %}
{% endwith %}

<!-- FLASH MESSAGES -->

app/templates/main/_footer.html
<ul class="nav justify-content-center border-bottom pb-3 mb-3">
    <li class="nav-item"><a href="#" class="nav-link px-2">Home</a></li>
    <li class="nav-item"><a href="#" class="nav-link px-2">Features</a></li>
    <li class="nav-item"><a href="#" class="nav-link px-2">Pricing</a></li>
    <li class="nav-item"><a href="#" class="nav-link px-2">FAQs</a></li>
    <li class="nav-item"><a href="#" class="nav-link px-2">About</a></li>
</ul>
<p class="text-center">© 2024 Company, Inc</p>

app/templates/main/_header.html
<div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
    <a href="{{ url_for('post.all') }}" class="d-flex align-items-center mb-2 mb-lg-0 text-white text-decoration-none">
      <img class="header_logo" src="{{ url_for('static', filename='img/main_logo.png') }}" alt="Главное лого">
    </a>

    <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
      <li><a href="{{ url_for('post.all') }}" class="nav-link px-2 text-secondary">Главная</a></li>
      {% if current_user.is_authenticated %}
        <li><a href="{{ url_for('post.create')}}" class="nav-link px-2 text-white">Добавить тему</a></li>
      {% endif %}
    </ul>

    <div class="text-end">
      {% if current_user.is_authenticated %}
        <span>{{ current_user.login }}</span>
        <a href="{{ url_for('user.logout')}}" class="btn btn-outline-light me-2">Выйти</a>
      {% else %}
        <a href="{{ url_for('user.login')}}" class="btn btn-outline-light me-2">Войти</a>
        <a href="{{ url_for('user.register')}}" class="btn btn-warning">Регистрация</a>
      {% endif %}
    </div>
  </div>

app/templates/main/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/libs/bootstrap.min.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/main.css') }}">
    {% block style %}{% endblock %}
    <title>{% block title %}{% endblock %}</title>
</head>

<body>
    <header>{% include 'main/_header.html' %}</header>

    <div class="page">
        <main class="content">
            {% include 'main/_flash.html' %}
            {% block content %}
            {% endblock %}
        </main>
        <footer class="py-3 my-4">
            {% include 'main/_footer.html' %}
        </footer>
    </div>



    <script src="{{ url_for('static', filename='js/libs/bootstrap.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/app.js') }}"></script>

</body>
</html>

app/templates/post/all.html
{% extends 'main/base.html' %}

{% block title %} Темы {% endblock %}

{% block style %}
<link rel="stylesheet" href="{{ url_for('static', filename='css/blocks/table.css') }}">
<link rel="stylesheet" href="{{ url_for('static', filename='css/libs/font-awesome.min.css') }}">
{% endblock %}

{% block content %}
<h3>Темы</h3>
<div class="table-responsive custom-table-responsive">
    <table class="table custom-table">
        <thead>
            <tr>
                <th scope="col">Преподаватель</th>
                <th scope="col">Тема</th>
                <th scope="col">Студент</th>
                {% if current_user.is_authenticated %} <th scope="col">Действие</th> {% endif %}
            </tr>
        </thead>
        <tbody>
            {% for post in posts %}
            <tr scope="row">
                <td>
                    <img src="{{url_for('static', filename='upload/'+post.author.avatar)}}" alt="Преподаватель">
                    {{post.author.name}}
                </td>
                <td>{{post.subject}}</td>
                <td>{{post.student}}</td>
                {% if current_user.is_authenticated %}
                    <td>
                            <a href="{{ url_for('post.update', id=post.id) }}" class="btn btn-sm btn-secondary"><span class="fa fa-edit"></span></a>
                            <a href="{{ url_for('post.delete', id=post.id) }}" class="btn btn-sm btn-danger"><span class="fa fa-trash"></span></a>                    
                    </td>
                {% endif %}
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}

app/templates/post/create.html
{% extends 'main/base.html' %}

{% block title %}
Добавление темы
{% endblock %}

{% block content %}
<h1>Добавление темы</h1>
<form method="post" class="form-control d-flex flex-column gap-2">
    <input name="subject" type="text" placeholder="Тема урока" class="form-control">
    {{ form.student }}
    <input value='Добавить' type="submit" class="btn btn-success">
</form>
{% endblock %}

app/templates/post/update.html
{% extends 'main/base.html' %}

{% block title %}
Редактирование темы
{% endblock %}

{% block content %}
<h1>Редактирование темы {{ post.id }}</h1>
<form method="post" class="form-control d-flex flex-column gap-2">
    <input value="{{post.teacher}}" name="teacher" type="text" placeholder="ФИО преподавателя" class="form-control">
    <input value="{{post.subject}}" name="subject" type="text" placeholder="Тема урока" class="form-control">
    <input value="{{post.student}}" name="student" type="text" placeholder="ФИО студента" class="form-control">
    <input value='Обновить' type="submit" class="btn btn-success">
</form>
{% endblock %}

app/templates/user/login.html
<!-- для логина прописали вторым способом в файле forms.py -->

{% extends 'main/base.html' %}

{% block title %} Авторизация {% endblock %}

{% block content %} 
<h1>Авторизация</h1>
<form method="post" class="form-control d-flex flex-column gap-2">
    {{ form.csrf_token }}
    {{ form.login }} 
    {{ form.password (class='form-control', placeholder='Пароль')}}
    <div class="d-flex flex-row justify-content-center gap-2">
        {{ form.remember.label }}{{ form.remember(class='form-check')  }}    
    </div>
    {{ form.submit (class='btn btn-success')}}
</form>
{% endblock %}

app/templates/user/register.html
<!-- для логина прописали вторым способом в файле forms.py -->

{% extends 'main/base.html' %}

{% block title %} Регистрация {% endblock %}

{% block content %} 
<h1>Регистрация</h1>
<form method="post" enctype="multipart/form-data" class="form-control d-flex flex-column gap-2">
    {{ form.csrf_token }}
    {{ form.name(class='form-control', placeholder='ФИО') }}
    {{ form.login }} 
    {% if form.login.errors %}
        <div class="invalid-feedback" style="display: block!important;">
            {% for error in form.login.errors %}
            <span>
                {{ error }}
            </span>
            {% endfor %}
        </div>
    {% endif %}
    {{ form.avatar (class='form-control')}}
    {{ form.password (class='form-control', placeholder='Пароль')}}
    {{ form.confirm_password (class='form-control', placeholder='Подтвердите пароль')}}
    {{ form.submit (class='btn btn-success')}}
</form>
{% endblock %}